-- **************************************** SqlDBM: Snowflake ***************************************
-- * Generated by SqlDBM: Hub and Spoke PDM - Policy Combined - Layer 3 by Jason.Bemont@beazley.com *


-- ************************************** HUB_POLICY_LINE
CREATE TABLE HUB_POLICY_LINE
(
 HUB_POLICY_LINE_HK   varchar(32) NOT NULL COMMENT 'Hash of business key.',
 SECTION_REFERENCE_NK varchar(16777216) NOT NULL COMMENT 'Natural business key (max length).
For Beazley Pro: Policy Number + Section Ref.',
 LOAD_DATETIME        timestamp_ntz NOT NULL COMMENT 'Load Datetime is the date and time upon which a record is loaded, typically during the ETL or ELT process.',
 RECORD_SOURCE_NAME   varchar(16777216) NOT NULL COMMENT 'Record Source Name is a string value that uniquely identifies the origin of a data record. It provides traceability back to a source system and an audit trail for data ingestion.  Often more specific in that it includes file name, batch ID, or API endpoint',
 SOURCE_SYSTEM_NAME   varchar(16777216) NOT NULL COMMENT 'Business-level identifier of the external system the data came from and is often a higher level.  For example, System Name can contain CRM, BILLING, ERP.',

 CONSTRAINT HUB_POLICY_LINE_PK PRIMARY KEY ( HUB_POLICY_LINE_HK ),
 CONSTRAINT HUB_POLICY_LINE_AK_1 UNIQUE ( SECTION_REFERENCE_NK )
);

-- ************************************** HUB_CONTACT
CREATE TABLE HUB_CONTACT
(
 HUB_CONTACT_HK     varchar(32) NOT NULL COMMENT 'Hash of business key.',
 CONTACT_NK         varchar(16777216) NOT NULL COMMENT 'Natural business key (max length).',
 LOAD_DATETIME      timestamp_ntz NOT NULL COMMENT 'Load Datetime is the date and time upon which a record is loaded, typically during the ETL or ELT process.',
 RECORD_SOURCE_NAME varchar(16777216) NOT NULL COMMENT 'Record Source Name is a string value that uniquely identifies the origin of a data record. It provides traceability back to a source system and an audit trail for data ingestion.  Often more specific in that it includes file name, batch ID, or API endpoint',
 SOURCE_SYSTEM_NAME varchar(16777216) NOT NULL COMMENT 'Business-level identifier of the external system the data came from and is often a higher level.  For example, System Name can contain CRM, BILLING, ERP.',

 CONSTRAINT HUB_CONTACT_PK PRIMARY KEY ( HUB_CONTACT_HK ),
 CONSTRAINT HUB_CONTACT_AK_1 UNIQUE ( CONTACT_NK )
);

-- ************************************** HUB_QUOTE
CREATE TABLE HUB_QUOTE
(
 HUB_QUOTE_HK       varchar(32) NOT NULL COMMENT 'Hash of business key.',
 QUOTE_NK           varchar(16777216) NOT NULL COMMENT 'Natural business key (max length).',
 LOAD_DATETIME      timestamp_ntz NOT NULL COMMENT 'Load Datetime is the date and time upon which a record is loaded, typically during the ETL or ELT process.',
 RECORD_SOURCE_NAME varchar(16777216) NOT NULL COMMENT 'Record Source Name is a string value that uniquely identifies the origin of a data record. It provides traceability back to a source system and an audit trail for data ingestion.  Often more specific in that it includes file name, batch ID, or API endpoint',
 SOURCE_SYSTEM_NAME varchar(16777216) NOT NULL COMMENT 'Business-level identifier of the external system the data came from and is often a higher level.  For example, System Name can contain CRM, BILLING, ERP.',

 CONSTRAINT HUB_QUOTE_PK PRIMARY KEY ( HUB_QUOTE_HK ),
 CONSTRAINT HUB_QUOTE_AK_1 UNIQUE ( QUOTE_NK )
);

-- ************************************** HUB_PRODUCT
CREATE TABLE HUB_PRODUCT
(
 HUB_PRODUCT_HK     varchar(32) NOT NULL COMMENT 'Hash of business key.',
 PRODUCT_NK         varchar(16777216) NOT NULL COMMENT 'Natural business key (max length).',
 LOAD_DATETIME      timestamp_ntz NOT NULL COMMENT 'Load Datetime is the date and time upon which a record is loaded, typically during the ETL or ELT process.',
 RECORD_SOURCE_NAME varchar(16777216) NOT NULL COMMENT 'Record Source Name is a string value that uniquely identifies the origin of a data record. It provides traceability back to a source system and an audit trail for data ingestion.  Often more specific in that it includes file name, batch ID, or API endpoint',
 SOURCE_SYSTEM_NAME varchar(16777216) NOT NULL COMMENT 'Business-level identifier of the external system the data came from and is often a higher level.  For example, System Name can contain CRM, BILLING, ERP.',

 CONSTRAINT HUB_PRODUCT_PK PRIMARY KEY ( HUB_PRODUCT_HK ),
 CONSTRAINT HUB_PRODUCT_AK_1 UNIQUE ( PRODUCT_NK )
);

-- ************************************** HUB_POLICY
CREATE TABLE HUB_POLICY
(
 HUB_POLICY_HK       varchar(32) NOT NULL COMMENT 'Hash of business key.',
 POLICY_REFERENCE_NK varchar(16777216) NOT NULL COMMENT 'Natural business key (max length).',
 LOAD_DATETIME       timestamp_ntz NOT NULL COMMENT 'Load Datetime is the date and time upon which a record is loaded, typically during the ETL or ELT process.',
 RECORD_SOURCE_NAME  varchar(16777216) NOT NULL COMMENT 'Record Source Name is a string value that uniquely identifies the origin of a data record. It provides traceability back to a source system and an audit trail for data ingestion.  Often more specific in that it includes file name, batch ID, or API endpoint',
 SOURCE_SYSTEM_NAME  varchar(16777216) NOT NULL COMMENT 'Business-level identifier of the external system the data came from and is often a higher level.  For example, System Name can contain CRM, BILLING, ERP.',

 CONSTRAINT HUB_POLICY_PK PRIMARY KEY ( HUB_POLICY_HK ),
 CONSTRAINT HUB_POLICY_AK_1 UNIQUE ( POLICY_REFERENCE_NK )
);

-- ************************************** HUB_DEDUCTION
CREATE TABLE HUB_DEDUCTION
(
 HUB_DEDUCTION_HK   varchar(32) NOT NULL COMMENT 'Hash of business key.',
 DEDUCTION_NK       varchar(16777216) NOT NULL COMMENT 'Natural business key (max length).',
 LOAD_DATETIME      timestamp_ntz NOT NULL COMMENT 'Load Datetime is the date and time upon which a record is loaded, typically during the ETL or ELT process.',
 RECORD_SOURCE_NAME varchar(16777216) NOT NULL COMMENT 'Record Source Name is a string value that uniquely identifies the origin of a data record. It provides traceability back to a source system and an audit trail for data ingestion.  Often more specific in that it includes file name, batch ID, or API endpoint',
 SOURCE_SYSTEM_NAME varchar(16777216) NOT NULL COMMENT 'Business-level identifier of the external system the data came from and is often a higher level.  For example, System Name can contain CRM, BILLING, ERP.',

 CONSTRAINT HUB_DEDUCTION_PK PRIMARY KEY ( HUB_DEDUCTION_HK ),
 CONSTRAINT HUB_DEDUCTION_AK_1 UNIQUE ( DEDUCTION_NK )
);

-- ************************************** HUB_TRANSACTION
CREATE TABLE HUB_TRANSACTION
(
 HUB_TRANSACTION_HK varchar(32) NOT NULL COMMENT 'Hash of business key.',
 TRANSACTION_NK     varchar(16777216) NOT NULL COMMENT 'Natural business key (max length).',
 LOAD_DATETIME      timestamp_ntz NOT NULL COMMENT 'Load Datetime is the date and time upon which a record is loaded, typically during the ETL or ELT process.',
 RECORD_SOURCE_NAME varchar(16777216) NOT NULL COMMENT 'Record Source Name is a string value that uniquely identifies the origin of a data record. It provides traceability back to a source system and an audit trail for data ingestion.  Often more specific in that it includes file name, batch ID, or API endpoint',
 SOURCE_SYSTEM_NAME varchar(16777216) NOT NULL COMMENT 'Business-level identifier of the external system the data came from and is often a higher level.  For example, System Name can contain CRM, BILLING, ERP.',

 CONSTRAINT HUB_TRANSACTION_PK PRIMARY KEY ( HUB_TRANSACTION_HK ),
 CONSTRAINT HUB_TRANSACTION_AK_1 UNIQUE ( TRANSACTION_NK )
);

-- ************************************** HUB_SUBMISSION
CREATE TABLE HUB_SUBMISSION
(
 HUB_SUBMISSION_HK  varchar(32) NOT NULL COMMENT 'Hash of business key.',
 SUBMISSION_NK      varchar(16777216) NOT NULL COMMENT 'Natural business key (max length).',
 LOAD_DATETIME      timestamp_ntz NOT NULL COMMENT 'Load Datetime is the date and time upon which a record is loaded, typically during the ETL or ELT process.',
 RECORD_SOURCE_NAME varchar(16777216) NOT NULL COMMENT 'Record Source Name is a string value that uniquely identifies the origin of a data record. It provides traceability back to a source system and an audit trail for data ingestion.  Often more specific in that it includes file name, batch ID, or API endpoint',
 SOURCE_SYSTEM_NAME varchar(16777216) NOT NULL COMMENT 'Business-level identifier of the external system the data came from and is often a higher level.  For example, System Name can contain CRM, BILLING, ERP.',

 CONSTRAINT HUB_SUBMISSION_PK PRIMARY KEY ( HUB_SUBMISSION_HK ),
 CONSTRAINT HUB_SUBMISSION_AK_1 UNIQUE ( SUBMISSION_NK )
);

-- ************************************** HUB_BROKER
CREATE TABLE HUB_BROKER
(
 HUB_BROKER_HK      varchar(32) NOT NULL COMMENT 'Hash of business key.',
 BROKER_NK          varchar(16777216) NOT NULL COMMENT 'Natural business key (max length).',
 CRM_ID             varchar(16777216),
 LLOYDS_ID          varchar(16777216),
 BROKER_NAME        varchar(16777216),
 LOAD_DATETIME      timestamp_ntz NOT NULL COMMENT 'Load Datetime is the date and time upon which a record is loaded, typically during the ETL or ELT process.',
 RECORD_SOURCE_NAME varchar(16777216) NOT NULL COMMENT 'Record Source Name is a string value that uniquely identifies the origin of a data record. It provides traceability back to a source system and an audit trail for data ingestion.  Often more specific in that it includes file name, batch ID, or API endpoint',
 SOURCE_SYSTEM_NAME varchar(16777216) NOT NULL COMMENT 'Business-level identifier of the external system the data came from and is often a higher level.  For example, System Name can contain CRM, BILLING, ERP.',

 CONSTRAINT HUB_BROKER_PK PRIMARY KEY ( HUB_BROKER_HK ),
 CONSTRAINT HUB_BROKER_AK_1 UNIQUE ( BROKER_NK )
)
COMMENT = 'HUB_BROKER natural key = CRM_ID + LLOYDS_ID + BROKER_NAME + SOURCE_SYSTEM_NAME; keep each component as a separate nullable column inside the hub.';

-- ************************************** HUB_BROKER_TYPE
CREATE TABLE HUB_BROKER_TYPE
(
 HUB_BROKER_TYPE_HK varchar(32) NOT NULL COMMENT 'Hash of business key.',
 BROKER_TYPE_NK     varchar(16777216) NOT NULL COMMENT 'Natural business key (max length).',
 LOAD_DATETIME      timestamp_ntz NOT NULL COMMENT 'Load Datetime is the date and time upon which a record is loaded, typically during the ETL or ELT process.',
 RECORD_SOURCE_NAME varchar(16777216) NOT NULL COMMENT 'Record Source Name is a string value that uniquely identifies the origin of a data record. It provides traceability back to a source system and an audit trail for data ingestion.  Often more specific in that it includes file name, batch ID, or API endpoint',
 SOURCE_SYSTEM_NAME varchar(16777216) NOT NULL COMMENT 'Business-level identifier of the external system the data came from and is often a higher level.  For example, System Name can contain CRM, BILLING, ERP.',

 CONSTRAINT HUB_BROKER_TYPE_PK PRIMARY KEY ( HUB_BROKER_TYPE_HK ),
 CONSTRAINT HUB_BROKER_AK_1 UNIQUE ( BROKER_TYPE_NK )
);

-- ************************************** SAT_POLICY_LINE_DETAIL_RAW
CREATE TABLE SAT_POLICY_LINE_DETAIL_RAW
(
 HUB_POLICY_LINE_HK        varchar(32) NOT NULL COMMENT 'Hash of business key.',
 LOAD_DATETIME             timestamp_ntz NOT NULL COMMENT 'Load Datetime is the date and time upon which a record is loaded, typically during the ETL or ELT process.',
 SECTION_STATUS_CODE       varchar(16777216),
 SECTION_STATUS_NAME       varchar(16777216) COMMENT 'From Eurobase, we get both the status code and status description. SECTION_STATUS_NAME in SAT_POLICY_LINE_DETAIL_RAW
From Eurobase we get both the status code and status description (name)
So separate out a SECTION STATUS CODE and SECTION STATUS NAME (Done)
TRIFOCUS_CODE (Eurobase logic provided by Anca right below)',
 EFFECTIVE_DATETIME        timestamp_ntz,
 EXPIRY_DATETIME           timestamp_ntz,
 TRIFOCUS_CODE             varchar(16777216) COMMENT 'Eurobase Logic: 
SELECT top 100 cob.cob_dept,--DISTINCT
cpd.cpd_policy_reference AS section_reference,
LEFT(cpd.cpd_policy_reference,8) AS policy_reference,
coalesce(foc.foc_area, cpd.cpd_tri_focus) AS TrifocusName
FROM PRD_DB.UNDRW_DEFAULT_020_STG.VW_EUROBASE_COMMON_POLICY_DETAILS_01 cpd
JOIN PRD_DB.UNDRW_DEFAULT_020_STG.VW_EUROBASE_POLICY_DETAILS_01         p ON cpd.cpd_policy_reference = p.pol_cpd_policy_reference
JOIN PRD_DB.UNDRW_DEFAULT_020_STG.VW_EUROBASE_POLICY_RISK_CLASS        prc ON cpd.cpd_policy_reference = prc.prc_cpd_policy_ref and prc_sequence_no = 1
LEFT JOIN PRD_DB.UNDRW_DEFAULT_020_STG.VW_EUROBASE_FOCUS_AREA_NEW foc ON (
						foc.foc_cob_code     = p.pol_cob_code AND 
						foc.foc_risk_class   = prc.prc_risk_class AND 
						foc.foc_mop_code     = p.pol_mop_code AND 
						foc.foc_udt_initials = cpd.cpd_udt_initials AND 
						foc.foc_stats_code   = p.pol_stats_code)
JOIN PRD_DB.UNDRW_DEFAULT_020_STG.VW_EUROBASE_COB_CODES               cob ON p.pol_cob_code = cob.cob_code
WHERE  cob.cob_dept = ''Specialty Lines''
 
UNION ALL
 
SELECT top 100 cob.cob_dept,--DISTINCT
cpd.cpd_policy_reference AS section_reference,
LEFT(cpd.cpd_policy_reference,8) AS policy_reference,
cob.cob_tri_group AS TrifocusName
FROM PRD_DB.UNDRW_DEFAULT_020_STG.VW_EUROBASE_COMMON_POLICY_DETAILS_01  cpd
JOIN PRD_DB.UNDRW_DEFAULT_020_STG.VW_EUROBASE_POLICY_DETAILS_01          p ON cpd.cpd_policy_reference = p.pol_cpd_policy_reference
JOIN PRD_DB.UNDRW_DEFAULT_020_STG.VW_EUROBASE_COB_CODES                   cob ON p.pol_cob_code = cob.cob_code
WHERE cob.cob_dept != ''Specialty Lines''join to MDM.Trifocus (PD view) to take the TrifocusCode',
 TRIFOCUS_NAME             varchar(16777216) COMMENT 'For TriFocus Name in Unirisx
= CASE  
WHEN cov.ProductName = ''UK CARGO/FREIGHT''		THEN ''UK Marine''
WHEN cov.ProductName = ''UK CARGO/FREIGHT 2012''	THEN ''UK Marine''
WHEN cov.ProductName = ''UK CARGO/FREIGHT v3''	THEN ''UK Marine''
WHEN cov.ProductName = ''UK HULL''				THEN ''UK Marine''
WHEN cov.ProductName = ''UK HULL 2012''			THEN ''UK Marine''
WHEN cov.ProductName = ''UK HULL v5''				THEN ''UK Marine''
												-- this is the logic they use in unirisx USBR to determine if a policy is ''V'' or ''W''
WHEN cov.ProductName LIKE ''US Builders Risk%'' AND cov.IssuingCompany LIKE ''%Beazley%Lloyd%''       THEN ''BUSA Engineering''
WHEN cov.ProductName LIKE ''US Builders Risk%'' AND cov.IssuingCompany LIKE ''%Beazley%Company%Inc%'' THEN ''BICI Engineering''
ELSE COALESCE(tri.TargetValue, cov.Trifocus)
END',
 ENTITY_PLATFORM_NAME      varchar(16777216),
 DISTRIBUTION_CHANNEL_NAME varchar(16777216),
 FOC_AREA_NAME             varchar(16777216),
 CPD_TRI_FOCUS_NAME        varchar(16777216),
 COB_TRI_GROUP_NAME        varchar(16777216),
 COB_DEPT_NAME             varchar(16777216),
 PRODUCT_NAME              varchar(16777216),
 ISSUING_COMPANY_NAME      varchar(16777216),
 PROCESS_ID                number(38) NOT NULL,
 END_DATETIME              timestamp_ntz NOT NULL,
 IS_CURRENT_FLAG           boolean NOT NULL,
 HASH_DIFF                 varchar(32) NOT NULL,
 RECORD_SOURCE_NAME        varchar(16777216) NOT NULL COMMENT 'Record Source Name is a string value that uniquely identifies the origin of a data record. It provides traceability back to a source system and an audit trail for data ingestion.  Often more specific in that it includes file name, batch ID, or API endpoint',
 SOURCE_SYSTEM_NAME        varchar(16777216) NOT NULL COMMENT 'Business-level identifier of the external system the data came from and is often a higher level.  For example, System Name can contain CRM, BILLING, ERP.',

 CONSTRAINT SAT_POLICY_LINE_DETAIL_RAW_PK PRIMARY KEY ( HUB_POLICY_LINE_HK, LOAD_DATETIME ),
 CONSTRAINT SAT_POLICY_LINE_DETAIL_RAW_HUB_POLICY_LINE_FK FOREIGN KEY ( HUB_POLICY_LINE_HK ) REFERENCES HUB_POLICY_LINE ( HUB_POLICY_LINE_HK )
);

-- ************************************** SAT_BROKER_DETAIL_RAW
CREATE TABLE SAT_BROKER_DETAIL_RAW
(
 HUB_BROKER_HK       varchar(32) NOT NULL COMMENT 'Hash of business key.',
 LOAD_DATETIME       timestamp_ntz NOT NULL COMMENT 'Load Datetime is the date and time upon which a record is loaded, typically during the ETL or ELT process.',
 ADDRESS_LINE_1_TEXT varchar(16777216),
 ADDRESS_LINE_2_TEXT varchar(16777216),
 CITY_NAME           varchar(16777216),
 COUNTY_NAME         varchar(16777216),
 COUNTRY_NAME        varchar(16777216),
 POSTAL_CODE         varchar(16777216),
 PROCESS_ID          number(38) NOT NULL,
 END_DATETIME        timestamp_ntz NOT NULL,
 IS_CURRENT_FLAG     boolean NOT NULL,
 HASH_DIFF           varchar(32) NOT NULL,
 RECORD_SOURCE_NAME  varchar(16777216) NOT NULL COMMENT 'Record Source Name is a string value that uniquely identifies the origin of a data record. It provides traceability back to a source system and an audit trail for data ingestion.  Often more specific in that it includes file name, batch ID, or API endpoint',
 SOURCE_SYSTEM_NAME  varchar(16777216) NOT NULL COMMENT 'Business-level identifier of the external system the data came from and is often a higher level.  For example, System Name can contain CRM, BILLING, ERP.',

 CONSTRAINT SAT_BROKER_DETAIL_RAW_PK PRIMARY KEY ( HUB_BROKER_HK, LOAD_DATETIME ),
 CONSTRAINT SAT_BROKER_DETAIL_RAW_HUB_BROKER_FK FOREIGN KEY ( HUB_BROKER_HK ) REFERENCES HUB_BROKER ( HUB_BROKER_HK )
)
COMMENT = 'HUB_BROKER natural key = CRM_ID + LLOYDS_ID + BROKER_NAME + SOURCE_SYSTEM_NAME; keep each component as a separate nullable column inside the hub.';

-- ************************************** SAT_POLICY_LINE_PREMIUM_RAW
CREATE TABLE SAT_POLICY_LINE_PREMIUM_RAW
(
 HUB_POLICY_LINE_HK     varchar(32) NOT NULL COMMENT 'Hash of business key.',
 LOAD_DATETIME          timestamp_ntz NOT NULL COMMENT 'Load Datetime is the date and time upon which a record is loaded, typically during the ETL or ELT process.',
 NET_PREMIUM_AMOUNT     number(38,2),
 GROSS_PREMIUM_AMOUNT   number(38,2),
 ORIGINAL_CURRENCY_NAME varchar(16777216),
 PROCESS_ID             number(38) NOT NULL,
 END_DATETIME           timestamp_ntz NOT NULL,
 IS_CURRENT_FLAG        boolean NOT NULL,
 HASH_DIFF              varchar(32) NOT NULL,
 RECORD_SOURCE_NAME     varchar(16777216) NOT NULL COMMENT 'Record Source Name is a string value that uniquely identifies the origin of a data record. It provides traceability back to a source system and an audit trail for data ingestion.  Often more specific in that it includes file name, batch ID, or API endpoint',
 SOURCE_SYSTEM_NAME     varchar(16777216) NOT NULL COMMENT 'Business-level identifier of the external system the data came from and is often a higher level.  For example, System Name can contain CRM, BILLING, ERP.',

 CONSTRAINT SAT_POLICY_LINE_PREMIUM_RAW_PK PRIMARY KEY ( HUB_POLICY_LINE_HK, LOAD_DATETIME ),
 CONSTRAINT SAT_POLICY_LINE_PREMIUM_RAW_HUB_POLICY_LINE_FK FOREIGN KEY ( HUB_POLICY_LINE_HK ) REFERENCES HUB_POLICY_LINE ( HUB_POLICY_LINE_HK )
);

-- ************************************** LNK_BROKER_POLICY
CREATE TABLE LNK_BROKER_POLICY
(
 LNK_BROKER_POLICY_HK varchar(32) NOT NULL COMMENT 'This is the hash of the concatenated keys from the linked hubs.',
 HUB_BROKER_HK        varchar(32) NOT NULL COMMENT 'Hash of business key.',
 HUB_POLICY_HK        varchar(32) NOT NULL COMMENT 'Hash of business key.',
 HUB_BROKER_TYPE_HK   varchar(32) NOT NULL COMMENT 'Hash of business key.',
 LOAD_DATETIME        timestamp_ntz NOT NULL COMMENT 'Load Datetime is the date and time upon which a record is loaded, typically during the ETL or ELT process.',
 RECORD_SOURCE_NAME   varchar(16777216) NOT NULL COMMENT 'Record Source Name is a string value that uniquely identifies the origin of a data record. It provides traceability back to a source system.',
 SOURCE_SYSTEM_NAME   varchar(16777216) NOT NULL COMMENT 'Business-level identifier of the external system the data came from and is often a higher level.  For example, System Name can contain CRM, BILLING, ERP.',

 CONSTRAINT LNK_BROKER_POLICY_PK PRIMARY KEY ( LNK_BROKER_POLICY_HK ),
 CONSTRAINT LNK_BROKER_POLICY_HUB_BROKER_FK FOREIGN KEY ( HUB_BROKER_HK ) REFERENCES HUB_BROKER ( HUB_BROKER_HK ),
 CONSTRAINT LNK_BROKER_POLICY_HUB_BROKER_TYPE_FK FOREIGN KEY ( HUB_BROKER_TYPE_HK ) REFERENCES HUB_BROKER_TYPE ( HUB_BROKER_TYPE_HK ),
 CONSTRAINT LNK_BROKER_POLICY_HUB_POLICY_FK FOREIGN KEY ( HUB_POLICY_HK ) REFERENCES HUB_POLICY ( HUB_POLICY_HK )
);

-- ************************************** LNK_POLICY_LINE_DEDUCTION
CREATE TABLE LNK_POLICY_LINE_DEDUCTION
(
 LNK_POLICY_LINE_DEDUCTION_HK varchar(32) NOT NULL COMMENT 'This is the hash of the concatenated keys from the linked hubs.',
 HUB_POLICY_LINE_HK           varchar(32) NOT NULL COMMENT 'Hash of business key.',
 HUB_DEDUCTION_HK             varchar(32) NOT NULL COMMENT 'Hash of business key.',
 LOAD_DATETIME                timestamp_ntz NOT NULL COMMENT 'Load Datetime is the date and time upon which a record is loaded, typically during the ETL or ELT process.',
 RECORD_SOURCE_NAME           varchar(16777216) NOT NULL COMMENT 'Record Source Name is a string value that uniquely identifies the origin of a data record. It provides traceability back to a source system.',
 SOURCE_SYSTEM_NAME           varchar(16777216) NOT NULL COMMENT 'Business-level identifier of the external system the data came from and is often a higher level.  For example, System Name can contain CRM, BILLING, ERP.',

 CONSTRAINT LNK_POLICY_LINE_DEDUCTION_PK PRIMARY KEY ( LNK_POLICY_LINE_DEDUCTION_HK ),
 CONSTRAINT LNK_POLICY_LINE_DEDUCTION_HUB_DEDUCTION_FK FOREIGN KEY ( HUB_DEDUCTION_HK ) REFERENCES HUB_DEDUCTION ( HUB_DEDUCTION_HK ),
 CONSTRAINT LNK_POLICY_LINE_DEDUCTION_HUB_POLICY_LINE_FK FOREIGN KEY ( HUB_POLICY_LINE_HK ) REFERENCES HUB_POLICY_LINE ( HUB_POLICY_LINE_HK )
);

-- ************************************** LNK_BROKER_CONTACT
CREATE TABLE LNK_BROKER_CONTACT
(
 LNK_BROKER_CONTACT_HK varchar(32) NOT NULL COMMENT 'This is the hash of the concatenated keys from the linked hubs.',
 HUB_BROKER_HK         varchar(32) NOT NULL COMMENT 'Hash of business key.',
 HUB_CONTACT_HK        varchar(32) NOT NULL COMMENT 'Hash of business key.',
 LOAD_DATETIME         timestamp_ntz NOT NULL COMMENT 'Load Datetime is the date and time upon which a record is loaded, typically during the ETL or ELT process.',
 RECORD_SOURCE_NAME    varchar(16777216) NOT NULL COMMENT 'Record Source Name is a string value that uniquely identifies the origin of a data record. It provides traceability back to a source system.',
 SOURCE_SYSTEM_NAME    varchar(16777216) NOT NULL COMMENT 'Business-level identifier of the external system the data came from and is often a higher level.  For example, System Name can contain CRM, BILLING, ERP.',

 CONSTRAINT LNK_BROKER_CONTACT_PK PRIMARY KEY ( LNK_BROKER_CONTACT_HK ),
 CONSTRAINT LNK_BROKER_CONTACT_HUB_BROKER_FK FOREIGN KEY ( HUB_BROKER_HK ) REFERENCES HUB_BROKER ( HUB_BROKER_HK ),
 CONSTRAINT LNK_BROKER_CONTACT_HUB_CONTACT_FK FOREIGN KEY ( HUB_CONTACT_HK ) REFERENCES HUB_CONTACT ( HUB_CONTACT_HK )
);

-- ************************************** LNK_POLICY_POLICY_LINE
CREATE TABLE LNK_POLICY_POLICY_LINE
(
 LNK_POLICY_POLICY_LINE_HK varchar(32) NOT NULL COMMENT 'This is the hash of the concatenated keys from the linked hubs.',
 HUB_POLICY_HK             varchar(32) NOT NULL COMMENT 'Hash of business key.',
 HUB_POLICY_LINE_HK        varchar(32) NOT NULL COMMENT 'Hash of business key.',
 LOAD_DATETIME             timestamp_ntz NOT NULL COMMENT 'Load Datetime is the date and time upon which a record is loaded, typically during the ETL or ELT process.',
 RECORD_SOURCE_NAME        varchar(16777216) NOT NULL COMMENT 'Record Source Name is a string value that uniquely identifies the origin of a data record. It provides traceability back to a source system.',
 SOURCE_SYSTEM_NAME        varchar(16777216) NOT NULL COMMENT 'Business-level identifier of the external system the data came from and is often a higher level.  For example, System Name can contain CRM, BILLING, ERP.',

 CONSTRAINT LNK_POLICY_POLICY_LINE_PK PRIMARY KEY ( LNK_POLICY_POLICY_LINE_HK ),
 CONSTRAINT LNK_POLICY_POLICY_LINE_HUB_POLICY_FK FOREIGN KEY ( HUB_POLICY_HK ) REFERENCES HUB_POLICY ( HUB_POLICY_HK ),
 CONSTRAINT LNK_POLICY_POLICY_LINE_HUB_POLICY_LINE_FK FOREIGN KEY ( HUB_POLICY_LINE_HK ) REFERENCES HUB_POLICY_LINE ( HUB_POLICY_LINE_HK )
);

-- ************************************** LNK_QUOTE_SUBMISSION
CREATE TABLE LNK_QUOTE_SUBMISSION
(
 LNK_QUOTE_SUBMISSION_HK varchar(32) NOT NULL COMMENT 'This is the hash of the concatenated keys from the linked hubs.',
 HUB_QUOTE_HK            varchar(32) NOT NULL COMMENT 'Hash of business key.',
 HUB_SUBMISSION_HK       varchar(32) NOT NULL COMMENT 'Hash of business key.',
 LOAD_DATETIME           timestamp_ntz NOT NULL COMMENT 'Load Datetime is the date and time upon which a record is loaded, typically during the ETL or ELT process.',
 RECORD_SOURCE_NAME      varchar(16777216) NOT NULL COMMENT 'Record Source Name is a string value that uniquely identifies the origin of a data record. It provides traceability back to a source system.',
 SOURCE_SYSTEM_NAME      varchar(16777216) NOT NULL COMMENT 'Business-level identifier of the external system the data came from and is often a higher level.  For example, System Name can contain CRM, BILLING, ERP.',

 CONSTRAINT LNK_QUOTE_SUBMISSION_PK PRIMARY KEY ( LNK_QUOTE_SUBMISSION_HK ),
 CONSTRAINT LNK_QUOTE_SUBMISSION_HUB_QUOTE_FK FOREIGN KEY ( HUB_QUOTE_HK ) REFERENCES HUB_QUOTE ( HUB_QUOTE_HK ),
 CONSTRAINT LNK_QUOTE_SUBMISSION_HUB_SUBMISSION_FK FOREIGN KEY ( HUB_SUBMISSION_HK ) REFERENCES HUB_SUBMISSION ( HUB_SUBMISSION_HK )
);

-- ************************************** LNK_PRODUCT_POLICY_LINE
CREATE TABLE LNK_PRODUCT_POLICY_LINE
(
 LNK_PRODUCT_POLICY_LINE_HK varchar(32) NOT NULL COMMENT 'This is the hash of the concatenated keys from the linked hubs.',
 HUB_PRODUCT_HK             varchar(32) NOT NULL COMMENT 'Hash of business key.',
 HUB_POLICY_LINE_HK         varchar(32) NOT NULL COMMENT 'Hash of business key.',
 LOAD_DATETIME              timestamp_ntz NOT NULL COMMENT 'Load Datetime is the date and time upon which a record is loaded, typically during the ETL or ELT process.',
 RECORD_SOURCE_NAME         varchar(16777216) NOT NULL COMMENT 'Record Source Name is a string value that uniquely identifies the origin of a data record. It provides traceability back to a source system.',
 SOURCE_SYSTEM_NAME         varchar(16777216) NOT NULL COMMENT 'Business-level identifier of the external system the data came from and is often a higher level.  For example, System Name can contain CRM, BILLING, ERP.',

 CONSTRAINT LNK_PRODUCT_POLICY_LINE_PK PRIMARY KEY ( LNK_PRODUCT_POLICY_LINE_HK ),
 CONSTRAINT LNK_PRODUCT_POLICY_LINE_HUB_POLICY_LINE_FK FOREIGN KEY ( HUB_POLICY_LINE_HK ) REFERENCES HUB_POLICY_LINE ( HUB_POLICY_LINE_HK ),
 CONSTRAINT LNK_PRODUCT_POLICY_LINE_HUB_PRODUCT_FK FOREIGN KEY ( HUB_PRODUCT_HK ) REFERENCES HUB_PRODUCT ( HUB_PRODUCT_HK )
);

-- ************************************** SAT_POLICY_DETAIL_RAW
CREATE TABLE SAT_POLICY_DETAIL_RAW
(
 HUB_POLICY_HK            varchar(32) NOT NULL COMMENT 'Hash of business key.',
 LOAD_DATETIME            timestamp_ntz NOT NULL COMMENT 'Load Datetime is the date and time upon which a record is loaded, typically during the ETL or ELT process.',
 POLICY_RENEWAL_INDICATOR varchar(10) COMMENT 'One consolidated POLICY_RENEWAL_INDICATOR (varchar) for all sources.',
 RENEWED_FROM_POLICY_ID   varchar(16777216) COMMENT 'Keep RENEWED_FROM_POLICY_ID for systems providing prior policy links.
Remove redundant POLICY_RISK_CLASS_ID field.',
 POLICY_STATUS_NAME       varchar(16777216),
 BIND_DATE                timestamp_ntz,
 INCEPTION_DATE           timestamp_ntz,
 EXPIRY_DATE              timestamp_ntz,
 PROCESS_ID               number(38) NOT NULL,
 END_DATETIME             timestamp_ntz NOT NULL,
 IS_CURRENT_FLAG          boolean NOT NULL,
 HASH_DIFF                varchar(32) NOT NULL,
 RECORD_SOURCE_NAME       varchar(16777216) NOT NULL COMMENT 'Record Source Name is a string value that uniquely identifies the origin of a data record. It provides traceability back to a source system and an audit trail for data ingestion.  Often more specific in that it includes file name, batch ID, or API endpoint',
 SOURCE_SYSTEM_NAME       varchar(16777216) NOT NULL COMMENT 'Business-level identifier of the external system the data came from and is often a higher level.  For example, System Name can contain CRM, BILLING, ERP.',

 CONSTRAINT SAT_POLICY_DETAIL_RAW_PK PRIMARY KEY ( HUB_POLICY_HK, LOAD_DATETIME ),
 CONSTRAINT SAT_POLICY_DETAIL_RAW_HUB_POLICY_FK FOREIGN KEY ( HUB_POLICY_HK ) REFERENCES HUB_POLICY ( HUB_POLICY_HK )
);

-- ************************************** LNK_POLICY_QUOTE
CREATE TABLE LNK_POLICY_QUOTE
(
 LNK_POLICY_QUOTE_HK varchar(32) NOT NULL COMMENT 'This is the hash of the concatenated keys from the linked hubs.',
 HUB_POLICY_HK       varchar(32) NOT NULL COMMENT 'Hash of business key.',
 HUB_QUOTE_HK        varchar(32) NOT NULL COMMENT 'Hash of business key.',
 LOAD_DATETIME       timestamp_ntz NOT NULL COMMENT 'Load Datetime is the date and time upon which a record is loaded, typically during the ETL or ELT process.',
 RECORD_SOURCE_NAME  varchar(16777216) NOT NULL COMMENT 'Record Source Name is a string value that uniquely identifies the origin of a data record. It provides traceability back to a source system.',
 SOURCE_SYSTEM_NAME  varchar(16777216) NOT NULL COMMENT 'Business-level identifier of the external system the data came from and is often a higher level.  For example, System Name can contain CRM, BILLING, ERP.',

 CONSTRAINT LNK_POLICY_QUOTE_PK PRIMARY KEY ( LNK_POLICY_QUOTE_HK ),
 CONSTRAINT LNK_POLICY_QUOTE_HUB_POLICY_FK FOREIGN KEY ( HUB_POLICY_HK ) REFERENCES HUB_POLICY ( HUB_POLICY_HK ),
 CONSTRAINT LNK_POLICY_QUOTE_HUB_QUOTE_FK FOREIGN KEY ( HUB_QUOTE_HK ) REFERENCES HUB_QUOTE ( HUB_QUOTE_HK )
);

-- ************************************** LNK_POLICY_LINE_TRANSACTION
CREATE TABLE LNK_POLICY_LINE_TRANSACTION
(
 LNK_POLICY_LINE_TRANSACTION_HK varchar(32) NOT NULL,
 HUB_POLICY_LINE_HK             varchar(32) NOT NULL COMMENT 'Hash of business key.',
 HUB_TRANSACTION_HK             varchar(32) NOT NULL COMMENT 'Hash of business key.',
 LOAD_DATETIME                  timestamp_ntz NOT NULL COMMENT 'Load Datetime is the date and time upon which a record is loaded, typically during the ETL or ELT process.',
 RECORD_SOURCE_NAME             varchar(16777216) NOT NULL COMMENT 'Record Source Name is a string value that uniquely identifies the origin of a data record. It provides traceability back to a source system.',
 SOURCE_SYSTEM_NAME             varchar(16777216) NOT NULL COMMENT 'Business-level identifier of the external system the data came from and is often a higher level.  For example, System Name can contain CRM, BILLING, ERP.',

 CONSTRAINT LNK_POLICY_LINE_TRANSACTION_PK PRIMARY KEY ( LNK_POLICY_LINE_TRANSACTION_HK ),
 CONSTRAINT LNK_POLICY_LINE_TRANSACTION_HUB_POLICY_LINE_FK FOREIGN KEY ( HUB_POLICY_LINE_HK ) REFERENCES HUB_POLICY_LINE ( HUB_POLICY_LINE_HK ),
 CONSTRAINT LNK_POLICY_LINE_TRANSACTION_HUB_TRANSACTION_FK FOREIGN KEY ( HUB_TRANSACTION_HK ) REFERENCES HUB_TRANSACTION ( HUB_TRANSACTION_HK )
);

-- ************************************** SAT_LNK_POLICY_LINE_DEDUCTION_RAW
CREATE TABLE SAT_LNK_POLICY_LINE_DEDUCTION_RAW
(
 LNK_POLICY_LINE_DEDUCTION_HK varchar(32) NOT NULL COMMENT 'This is the hash of the concatenated keys from the linked hubs.',
 LOAD_DATETIME                timestamp_ntz NOT NULL COMMENT 'Load Datetime is the date and time upon which a record is loaded, typically during the ETL or ELT process.',
 DEDUCTION_AMOUNT             number(38,2),
 DEDUCTION_PERCENT            number(38,2),
 DEDUCTION_TYPE_NAME          varchar(16777216),
 PROCESS_ID                   number(38) NOT NULL,
 END_DATETIME                 timestamp_ntz NOT NULL,
 IS_CURRENT_FLAG              boolean NOT NULL,
 HASH_DIFF                    varchar(32) NOT NULL,
 RECORD_SOURCE_NAME           varchar(16777216) NOT NULL COMMENT 'Record Source Name is a string value that uniquely identifies the origin of a data record. It provides traceability back to a source system and an audit trail for data ingestion.  Often more specific in that it includes file name, batch ID, or API endpoint',
 SOURCE_SYSTEM_NAME           varchar(16777216) NOT NULL COMMENT 'Business-level identifier of the external system the data came from and is often a higher level.  For example, System Name can contain CRM, BILLING, ERP.',

 CONSTRAINT SAT_LNK_POLICY_LINE_DEDUCTION_RAW_PK PRIMARY KEY ( LNK_POLICY_LINE_DEDUCTION_HK, LOAD_DATETIME ),
 CONSTRAINT SAT_LNK_POLICY_LINE_DEDUCTION_RAW_LNK_POLICY_LINE_DEDUCTION_FK FOREIGN KEY ( LNK_POLICY_LINE_DEDUCTION_HK ) REFERENCES LNK_POLICY_LINE_DEDUCTION ( LNK_POLICY_LINE_DEDUCTION_HK )
);

-- ************************************** SAT_LNK_POLICY_LINE_TRANSACTION_RAW
CREATE TABLE SAT_LNK_POLICY_LINE_TRANSACTION_RAW
(
 LNK_POLICY_LINE_TRANSACTION_HK varchar(32) NOT NULL,
 LOAD_DATETIME                  timestamp_ntz NOT NULL COMMENT 'Load Datetime is the date and time upon which a record is loaded, typically during the ETL or ELT process.',
 TRANSACTION_DATE               timestamp_ntz,
 TRANSACTION_AMOUNT             number(38,2),
 TRANSACTION_TYPE_NAME          varchar(16777216),
 TRANSACTION_CURRENCY_NAME      varchar(16777216),
 PROCESS_ID                     number(38) NOT NULL,
 END_DATETIME                   timestamp_ntz NOT NULL,
 IS_CURRENT_FLAG                boolean NOT NULL,
 HASH_DIFF                      varchar(32) NOT NULL,
 RECORD_SOURCE_NAME             varchar(16777216) NOT NULL COMMENT 'Record Source Name is a string value that uniquely identifies the origin of a data record. It provides traceability back to a source system and an audit trail for data ingestion.  Often more specific in that it includes file name, batch ID, or API endpoint',
 SOURCE_SYSTEM_NAME             varchar(16777216) NOT NULL COMMENT 'Business-level identifier of the external system the data came from and is often a higher level.  For example, System Name can contain CRM, BILLING, ERP.',
 HUB_TRANSACTION_HK             varchar(32) NOT NULL COMMENT 'Hash of business key.',

 CONSTRAINT SAT_LNK_POLICY_LINE_TRANSACTION_RAW_PK PRIMARY KEY ( LNK_POLICY_LINE_TRANSACTION_HK, LOAD_DATETIME ),
 CONSTRAINT SAT_LNK_POLICY_LINE_TRANSACTION_RAW_LNK_POLICY_LINE_TRANSACTION_FK FOREIGN KEY ( LNK_POLICY_LINE_TRANSACTION_HK ) REFERENCES LNK_POLICY_LINE_TRANSACTION ( LNK_POLICY_LINE_TRANSACTION_HK )
);

